import 'package:solvoca/study/models.dart';

const seedListNames = ['일상', '사람', '일', '이동', '생각'];

const _seedPairsByList = <String, List<(String front, String back)>>{
  '일상': [
    ('hello', '안녕'),
    ('good morning', '좋은 아침'),
    ('good night', '잘 자'),
    ('thank you', '고마워'),
    ('please', '부탁해'),
    ('sorry', '미안해'),
    ('excuse me', '실례합니다'),
    ('how are you', '잘 지내?'),
    ('nice to meet you', '만나서 반가워'),
    ('see you later', '나중에 봐'),
    ('take care', '잘 지내'),
    ('help', '도와줘'),
    ('wait', '기다려'),
    ('stop', '멈춰'),
    ('start', '시작해'),
    ('open', '열어'),
    ('close', '닫아'),
    ('eat', '먹어'),
    ('drink', '마셔'),
    ('sleep', '자'),
    ('wake up', '일어나'),
    ('home', '집'),
    ('work', '일'),
    ('rest', '쉬어'),
    ('busy', '바빠'),
    ('free', '한가해'),
    ('hot', '더워'),
    ('cold', '추워'),
    ('rain', '비'),
    ('sunny', '맑아'),
    ('today', '오늘'),
    ('tomorrow', '내일'),
    ('yesterday', '어제'),
    ('again', '다시'),
    ('always', '항상'),
    ('sometimes', '가끔'),
    ('never', '절대 안'),
    ('maybe', '아마'),
    ('sure', '물론'),
    ('really', '정말'),
  ],
  '사람': [
    ('friend', '친구'),
    ('family', '가족'),
    ('mother', '엄마'),
    ('father', '아빠'),
    ('brother', '형/오빠/동생'),
    ('sister', '언니/누나/동생'),
    ('child', '아이'),
    ('baby', '아기'),
    ('teacher', '선생님'),
    ('student', '학생'),
    ('doctor', '의사'),
    ('nurse', '간호사'),
    ('neighbor', '이웃'),
    ('boss', '상사'),
    ('colleague', '동료'),
    ('team', '팀'),
    ('name', '이름'),
    ('age', '나이'),
    ('birthday', '생일'),
    ('person', '사람'),
    ('people', '사람들'),
    ('man', '남자'),
    ('woman', '여자'),
    ('boy', '소년'),
    ('girl', '소녀'),
    ('husband', '남편'),
    ('wife', '아내'),
    ('couple', '커플'),
    ('guest', '손님'),
    ('host', '주인'),
    ('leader', '리더'),
    ('member', '멤버'),
    ('partner', '파트너'),
    ('stranger', '낯선 사람'),
    ('crowd', '사람들'),
    ('smile', '미소'),
    ('laugh', '웃음'),
    ('cry', '울음'),
    ('voice', '목소리'),
    ('face', '얼굴'),
  ],
  '일': [
    ('meeting', '회의'),
    ('email', '이메일'),
    ('call', '전화'),
    ('message', '메시지'),
    ('report', '보고서'),
    ('plan', '계획'),
    ('task', '할 일'),
    ('deadline', '마감'),
    ('project', '프로젝트'),
    ('office', '사무실'),
    ('desk', '책상'),
    ('computer', '컴퓨터'),
    ('phone', '휴대폰'),
    ('break', '휴식'),
    ('lunch', '점심'),
    ('schedule', '일정'),
    ('goal', '목표'),
    ('result', '결과'),
    ('problem', '문제'),
    ('solution', '해결책'),
    ('idea', '아이디어'),
    ('question', '질문'),
    ('answer', '답'),
    ('check', '확인'),
    ('finish', '끝내'),
    ('submit', '제출'),
    ('review', '검토'),
    ('update', '업데이트'),
    ('share', '공유'),
    ('save', '저장'),
    ('delete', '삭제'),
    ('create', '만들'),
    ('edit', '수정'),
    ('search', '검색'),
    ('download', '다운로드'),
    ('upload', '업로드'),
    ('login', '로그인'),
    ('password', '비밀번호'),
    ('account', '계정'),
    ('teamwork', '협업'),
  ],
  '이동': [
    ('go', '가'),
    ('come', '와'),
    ('leave', '떠나'),
    ('arrive', '도착'),
    ('walk', '걸어'),
    ('run', '달려'),
    ('drive', '운전해'),
    ('ride', '타'),
    ('bus', '버스'),
    ('subway', '지하철'),
    ('train', '기차'),
    ('taxi', '택시'),
    ('car', '자동차'),
    ('bike', '자전거'),
    ('airport', '공항'),
    ('station', '역'),
    ('ticket', '표'),
    ('map', '지도'),
    ('road', '길'),
    ('street', '거리'),
    ('left', '왼쪽'),
    ('right', '오른쪽'),
    ('straight', '직진'),
    ('turn', '돌아'),
    ('near', '가까이'),
    ('far', '멀리'),
    ('here', '여기'),
    ('there', '거기'),
    ('where', '어디'),
    ('direction', '방향'),
    ('traffic', '교통'),
    ('light', '신호'),
    ('crosswalk', '횡단보도'),
    ('stopover', '경유'),
    ('trip', '여행'),
    ('travel', '여행하다'),
    ('visit', '방문'),
    ('return', '돌아오'),
    ('move', '이동'),
    ('fast', '빨리'),
    ('slow', '천천히'),
  ],
  '생각': [
    ('think', '생각해'),
    ('know', '알아'),
    ('believe', '믿어'),
    ('remember', '기억해'),
    ('forget', '잊어'),
    ('understand', '이해해'),
    ('learn', '배워'),
    ('study', '공부해'),
    ('decide', '결정해'),
    ('choose', '골라'),
    ('hope', '바라'),
    ('worry', '걱정해'),
    ('feel', '느껴'),
    ('like', '좋아해'),
    ('love', '사랑해'),
    ('hate', '싫어해'),
    ('want', '원해'),
    ('need', '필요해'),
    ('try', '시도해'),
    ('change', '바꿔'),
    ('focus', '집중해'),
    ('mind', '마음'),
    ('heart', '마음/심장'),
    ('reason', '이유'),
    ('truth', '진실'),
    ('lie', '거짓말'),
    ('guess', '추측'),
    ('mean', '의미하다'),
    ('mean', '뜻하다'),
    ('opinion', '의견'),
    ('idea', '생각'),
    ('dream', '꿈'),
    ('plan', '생각/계획'),
    ('doubt', '의심'),
    ('trust', '신뢰'),
    ('care', '신경 써'),
    ('calm', '차분해'),
    ('stress', '스트레스'),
    ('happy', '행복해'),
    ('sad', '슬퍼'),
    ('proud', '자랑스러워'),
  ],
};

StoreData buildSeedData() {
  final lists = <StudyList>[];
  final cards = <Card>[];

  for (final name in seedListNames) {
    final listId = 'list-$name';
    lists.add(StudyList(id: listId, name: name));

    final pairs = _seedPairsByList[name]!;
    for (var i = 0; i < pairs.length; i++) {
      final (front, back) = pairs[i];
      cards.add(
        Card(
          id: '$listId-card-$i',
          listId: listId,
          front: front,
          back: back,
          progress: CardProgress.cardNew,
          streak: 0,
        ),
      );
    }
  }

  return StoreData(lists: lists, cards: cards);
}
